[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"

[[services]]
name = "russkaya-familie-bot"

[services.healthcheck]
path = "/health"
timeout = 30
interval = 60

[[services.volumes]]
mountPath = "/tmp"
size = "1GB"

[nixpacks]
node_version = "18"
